services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: matsinhe
      POSTGRES_PASSWORD: matsinhe
    ports:
      - '5432:5432'